#!/bin/bash


main()
{
	[ -z "$1" ] && return

	WD=~/Arduino/"$1"
	FN="$1".ino

	mkdir -p "$WD"

	[ -e "$WD/$FN" ] && {
		echo Error: Will not overwrite existing file "$WD/$FN"
		return 1
	}

	cat > "$WD/$FN" <<-EOF
	void setup()
	{
	  // put your setup code here, to run once:

	}

	void loop()
	{
	  // put your main code here, to run repeatedly:

	}
EOF

	xterm -e sh -c cd\ "$WD"\ \;\ vim\ "$FN"
}

main "$1"
