colorscheme sienna

set gfn=Bitstream\ Vera\ Sans\ Mono\ 10   " a decent font
set lines=50 columns=165                  " window size

" window title
set titlestring=%{getcwd()}\ %{string(map(range(1,tabpagenr('$')),'tabpagewinnr(v:val,\"$\")'))}\ %{v:servername}

" hack for dealing with vims extremely slow 'terminal emulation'
" all shell commands are executed in xterm

hi SpecialKey  guifg=#b0b0b0
hi DiffAdd     guibg=#e8ffff
hi DiffChange  guibg=#fff0f0
hi DiffDelete  guibg=LightCyan
hi DiffText    guibg=#ffd0d0
hi Search      guibg=#90ff90

" these color stuff goes well with sienna
" use autocmd to make sure they stick!
autocmd ColorScheme * hi SpecialKey  guifg=#b0b0b0
autocmd ColorScheme * hi DiffAdd     guibg=#e8ffff
autocmd ColorScheme * hi DiffChange  guibg=#fff0f0
autocmd ColorScheme * hi DiffDelete  guibg=LightCyan
autocmd ColorScheme * hi DiffText    guibg=#ffd0d0
autocmd ColorScheme * hi Search      guibg=#90ff90

" buttons for jumping between next/prev tag with same name
menu ToolBar.-sep10- <nop>
menu icon=previous ToolBar.tprev :tprev<CR>
menu icon=next     ToolBar.tnext :tnext<CR>

map <C-Tab> gt
map <C-S-Tab> gT

map <S-ScrollWheelUp> [[
map <S-ScrollWheelDown> ]]

map <C-ScrollWheelDown> :cnext<CR>
map <C-ScrollWheelUp> :cprev<CR>

map <C-S-ScrollWheelDown> :SmallerFont<CR>
map <C-S-ScrollWheelUp> :LargerFont<CR>

map <M-Right> <C-W>>
map <M-Left> <C-W><

